[pytest]
testpaths = tests
addopts =
    --cov=src
    --cov-report=term-missing
    --cov-report=html:docs/test-reports/coverage
    --cov-report=xml:docs/test-reports/coverage.xml
    --alluredir=docs/test-reports/allure-results
